### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by laytonjb** [CFD-Institute/Euler2D-KFVS#1]
Truong,

I am trying to compile the code using the PGI 18.7 compilers and I'm running into an error. I use pgfortran as the compiler and get the following output:

make
pgfortran  -c mod_vector_algebra.f90
pgfortran  -c mod_read_gmsh.f90
pgfortran  -c mod_point_util.f90
pgfortran  -c mod_cell_2D.f90
pgfortran  -c mod_detect_nearest_neighbor.f90
PGF90-S-0155-detect_neighbor is use associated and cannot be redeclared (mod_detect_nearest_neighbor.f90: 7)
  0 inform,   0 warnings,   1 severes, 0 fatal for detect_neighbor
make: *** [mod_detect_nearest_neighbor.o] Error 2

It looks like mod_cell_2D.f90 and mod_detect_nearest_neighbor.f90 both have subroutines "detect_neighbor":

grep detect_neighbor *.f90
mod_cell_2D.f90:        procedure :: find_neighbor    => detect_neighbor
mod_cell_2D.f90:    subroutine detect_neighbor(this)
mod_detect_nearest_neighbor.f90:      subroutine detect_neighbor

Is this a bug in the code?

Thank you!

Jeff Layton

**Comment by trgdang** [comment]
Hi Layton,

I don't think so. 
find_neighbor is a type-bounded procedure of the derived type obj_cell_2D, and obj_cell_2D is a subclass of obj_gmsh_reader.   
In my version which is nearly the same version in branch master, obj_cell_2D is put in the same module mod_cell_2D, the source file is named mod_cell_2D.f90
You got the error probably because you put obj_cell_2D in another source file, mod_detect_nearest_neighbor.f90
If you put obj_cell_2D in mod_detect_nearest_neighbor.f90, then delete the obj_cell_2D in mod_cell_2D.f90

Best regards,
Truong

**Comment by trgdang** [comment]
Oops, I just knew the reason why you got the error. This repository contains all the necessary source files, you don't need to collect the old source files from my previous repository.
